feat(#I28): Basic parsing
Oktosha/codam-minishell pull request #31
Opened 2023-08-08 07:31 UTC by elenavoronin

Basic parsing is working with commands and pipes only. 
PS. The tests for parsing need adjusting, the printing part of the token is still not working. will adjust in new issue.

2023-08-09 10:07 UTC, elenavoronin commented
Need to talk about: parse action not working and parse testing

2023-08-10 19:03 UTC, Oktosha requested changes

2023-08-10 19:03 UTC, Oktosha commented on kotishell/src/lex/lex_a.c
> +// void	l_lx_start(t_lx_so_far *so_far, t_li_node *tk_tk)
?

2023-08-10 20:12 UTC, Oktosha approved these changes

2023-08-10 20:13 UTC, merged